### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by juuk100** [Picovoice/koala#65]
I am developing in iOS Objective C language.
Can I get sample code in Objective C language?

**Comment by albho** [comment]
@juuk100 - Unfortunately, we currently do not support Objective-C.

If this is for a commercial product, you can reach out to your sales contact at Picovoice, or otherwise [contact us](https://picovoice.ai/pricing/) through sales to get the feature added. We'd also be happy to consider a PR if you are interested in contributing.
